---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
            exclude: \.(pdb|gro|top|sdf)$
          - id: debug-statements
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v3.1.0
      hooks:
          - id: add-trailing-comma
    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
          - id: isort
    - repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.11.1
      hooks:
          - id: pyupgrade
            args: [--py38-plus]
    - repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
          - id: black
          - id: black-jupyter
            files: ^notebooks
    - repo: https://github.com/nbQA-dev/nbQA
      rev: 1.7.0
      hooks:
          - id: nbqa-black
            files: ^notebooks
          - id: nbqa-isort
            files: ^notebooks
          - id: nbqa-pyupgrade
            files: ^notebooks
            args:
                - --py38-plus
