---
name: openff-env
channels:
    - jaimergp/label/unsupported-cudatoolkit-shim
    - conda-forge
dependencies:
    - jupyterlab
    - openff-toolkit-examples ==0.14.3
    - openff-nagl ==0.3.1
    - openff-nagl-models ==0.1
