---
name: openff-env
channels:
    - jaimergp/label/unsupported-cudatoolkit-shim
    - conda-forge
    #- openeye
dependencies:
    - jupyterlab
    - openff-toolkit-examples =0.13.2
    #- smirnoff-plugins 
    - openff-bespokefit
    - xtb-python
    - nomkl
    - nb_conda_kernels
    - openff-nagl=0.2
    - openff-nagl-models
    # Optional, requires a free-for-academics license: https://www.eyesopen.com/academic-licensing
    #- openeye-toolkits
